# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20160601_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 8, 1, 28, 216074), verbose_name='date joined'),
        ),
    ]
