# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20160601_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 8, 26, 17, 633110), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
