# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_auto_20160602_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated',
        ),
    ]
